# Generated by Django 5.1.3 on 2024-11-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Outro', 'Other')], max_length=6)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('palavra_passe', models.CharField(max_length=50)),
                ('registo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.registo')),
            ],
        ),
    ]
